name: ci

# workflow triggers
on:
  push:
    branches:
      - '**' # every branch
    tags:
      - '**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  formatter:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - name: Set up uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          version: "0.12.8"
          enable-cache: true
          python-version: '3.14'
      - name: Install dependencies
        run: uv sync --locked
      - name: Check lint and formatting
        run: |
          uv run ruff check .
          uv run ruff format --check .

  coverage:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - name: Set up uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          version: "0.12.8"
          enable-cache: true
          python-version: '3.14'
      - name: Install dependencies
        run: uv sync --locked
      - name: Run tests
        run: uv run -m unittest -b

  # check if the makefile recipes are valid
  makefile:
    # needs: [test-and-build, docs]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - name: Set up uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          version: "0.12.8"
          enable-cache: true
          python-version: '3.14'
      - name: Check Makefile recipes
        run: |
          make install
          make tests
          make docs
